[package]
authors = ["Daniel Garcia <danigm@wadobo.com>"]
build = "build.rs"
name = "fractal-gtk"
version = "0.1.5"
workspace = "../"

[dependencies]
failure = "0.1.1"
gdk = "0.7.0"
gdk-pixbuf = "0.3.0"
gdk-pixbuf-sys = "0.5.0"
gio = "0.3.0"
glib = "0.4.0"
notify-rust = "3.4.2"
pango = "0.3.0"
regex = "0.2.3"
secret-service = "0.4.0"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.6"
url = "1.6.0"

[dependencies.cairo-rs]
features = ["png"]
version = "0.3.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.fractal-api]
path = "../fractal-api"

[dependencies.gtk]
features = ["v3_22"]
version = "0.3.0"
